# Generated by Django 2.2.7 on 2019-11-21 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='WebUser',
            fields=[
                ('user_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('pw', models.CharField(max_length=10)),
                ('birth', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=1)),
                ('subject', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Rentlist1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=20)),
                ('isbn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Book')),
            ],
        ),
    ]
