# Generated by Django 2.2.7 on 2019-11-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentlist',
            name='user_id',
            field=models.CharField(max_length=10),
        ),
    ]
