# Generated by Django 2.2.6 on 2019-11-14 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20191114_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10)),
                ('isbn', models.CharField(max_length=13)),
                ('date', models.CharField(max_length=20)),
            ],
        ),
    ]
