# Generated by Django 2.2.7 on 2019-11-27 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20191126_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Book')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.WebUser')),
            ],
        ),
    ]
